version: "3"

services:
  server:
    container_name: reparauto
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./:/srv/app
    depends_on:
      - db
    networks:
      - reparauto-network
    build: "./"

  db:
    container_name: mysql-reparauto
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - reparauto-db:/var/lib/mysql
    networks:
      - reparauto-network

volumes:
  reparauto-db:

networks:
  reparauto-network:
